### ISSUE TITLE
Side scrolling on content tabs

### ISSUE THREAD

**Issue by AlasdairBennett** [brianjmorris/brianmorris.info#2]
Currently the behaviour of side scrolling on content tabs (such as education) behaves very poorly when controlled via trackpad (tested on chrome, on macOS.) Instead of remaining where you've scrolled to, the page will bounce back and forth, and will usually settle someplace that seems to be near the middle.

In addition (and this might be a separate issue?) through scrolling it is possible to go beyond where one might expect to scroll through. This might be a matter of taste, but this behaviour feels unexpected for me. Example below.
![Screen Shot 2019-11-14 at 10 58 24 AM](https://user-images.githubusercontent.com/51632167/68874424-2f502580-06cf-11ea-8d8a-cdf4c5e4f405.png)

**Comment by brianjmorris** [comment]
Thanks @AlasdairBennett, side scrolling has been removed and will not likely return. Flexbox, with vertical scrolling, is now implemented.
